/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PureSVGInterface extends ethers.utils.Interface {
  functions: {
    "bytes32ToString(bytes32)": FunctionFragment;
    "formatTokenURI(string)": FunctionFragment;
    "svgToImageURI()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bytes32ToString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "formatTokenURI",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "svgToImageURI",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "bytes32ToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "formatTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "svgToImageURI",
    data: BytesLike
  ): Result;

  events: {};
}

export class PureSVG extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PureSVGInterface;

  functions: {
    bytes32ToString(
      _bytes32: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    formatTokenURI(
      imageURI: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    svgToImageURI(overrides?: CallOverrides): Promise<[string]>;
  };

  bytes32ToString(
    _bytes32: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  formatTokenURI(imageURI: string, overrides?: CallOverrides): Promise<string>;

  svgToImageURI(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    bytes32ToString(
      _bytes32: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    formatTokenURI(
      imageURI: string,
      overrides?: CallOverrides
    ): Promise<string>;

    svgToImageURI(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    bytes32ToString(
      _bytes32: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    formatTokenURI(
      imageURI: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    svgToImageURI(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bytes32ToString(
      _bytes32: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    formatTokenURI(
      imageURI: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    svgToImageURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
