/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { INFTSVG, INFTSVGInterface } from "../INFTSVG";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class INFTSVG__factory {
  static readonly abi = _abi;
  static createInterface(): INFTSVGInterface {
    return new utils.Interface(_abi) as INFTSVGInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFTSVG {
    return new Contract(address, _abi, signerOrProvider) as INFTSVG;
  }
}
